### ISSUE TITLE
Problem Running Tool

### ISSUE THREAD

**Issue by wnardo** [BroadbentT/RAM-MASTER#1]
____      _    __  __    __  __    _    ____ _____ _____ ____
|  _ \    / \  |  \/  |  |  \/  |  / \  / ___|_   _| ____|  _ \
| |_) |  / _ \ | |\/| |  | |\/| | / _ \ \___ \ | | |  _| | |_) |
|  _ <  / ___ \| |  | |  | |  | |/ ___ \ ___) || | | |___|  _ <
|_| \_\/_/   \_\_|  |_|  |_|  |_/_/   \_\____/ |_| |_____|_| \_\

BY TERENCE BROADBENT MSc DIGITAL FORENSICS & CYBERCRIME ANALYSIS

Booting - Please wait...

sh: 1: volatility: not found
Traceback (most recent call last):
  File "RamMaster.py", line 178, in <module>
    profiles = profiles.replace("Suggested Profile(s) :","")
NameError: name 'profiles' is not defined

**Comment by BroadbentT** [comment]
Hi thanks for the feedback. I am not sure why this would happen? This most likely answer is that the memory file you are using is  a Linux or Mac. The program is only really configured to bed used on Windows profiles. the ones listed in a profiles.txt.  I suggest that you find the line  "profiles = line" located just above the error line reported, and add 'print profiles' just below it. Let me know what it states or send me a link to the memory file that you are using and I will try and reproduce the error locally. That all said, I will be updating the program tonight to catch this error,  and will try to provide a better error message output. Pull down the latest version later tonight or tomorrow morning and see if the problem has been resolved.

**Comment by BroadbentT** [comment]
That all said, I have now updated the program to produce a log file called 'image.log' if this type of error occurs again. Pull down the latest version of the program, and let me know if the log file provides you with an answer, or just let me know how you get on generally with the updated version of RamMaster (which also includes a fix for an unreported issue of whitespace within the filename, which could have been the source of this particular error too).

**Comment by BroadbentT** [comment]
That all said, I have now updated the program to produce a log file called 'image.log' if this type of error occurs again. Pull down the latest version of the program, and let me know if the log file provides you with an answer, or just let me know how you get on generally with the updated version of RamMaster (which also includes a fix for an unreported issue of whitespace within the filename, which could have been the source of this particular error too).
